version: '3.8'

services:
  ssl:
    extends:
      file: docker-common.yml
      service: apache
    volumes:
      - ./ssl/ssl.conf:/usr/local/apache2/conf/extra/ssl.conf
      - ./ssl/server.crt:/usr/local/apache2/conf/server.crt
      - ./ssl/server.key:/usr/local/apache2/conf/server.key
      - ./ssl/index.html:/usr/local/apache2/htdocs/index.html
  
  reverse-proxy:
    extends:
      file: docker-common.yml
      service: apache
    volumes:
      - ./reverse-proxy/r-proxy.conf:/usr/local/apache2/conf/extra/r-proxy.conf
    depends_on:
      - reverse-proxy-node
      
  reverse-proxy-node:
    build: reverse-proxy 
    image: reverse-proxy-node
    container_name: reverse-proxy-node

  load-balancer:
    extends:
      file: docker-common.yml
      service: apache
    volumes:
      - ./load-balancer/l-balancer.conf:/usr/local/apache2/conf/extra/l-balancer.conf
    depends_on:
      - load-balancer-node

  load-balancer-node:
    build: load-balancer
    image: load-balancer-node
    container_name: load-balancer-node

  wsgi-app:
    build: wsgi
    image: wsgi-app
    container_name: wsgi-app

  wsgi:
    extends:
      file: docker-common.yml
      service: apache
    volumes:
      - ./wsgi/wsgi.conf:/usr/local/apache2/conf/extra/wsgi.conf
    depends_on:
      - wsgi-app

  django-app:
    build: django
    volumes:
      - /usr/src/app/.venv
      - static:/var/www/app/static

  django:
    extends:
      file: docker-common.yml
      service: apache
    volumes:
      - ./django/django.conf:/usr/local/apache2/conf/extra/django.conf
      - ./ssl/server.crt:/usr/local/apache2/conf/server.crt
      - ./ssl/server.key:/usr/local/apache2/conf/server.key
      - static:/var/www/app/static:ro
    depends_on:
      - django-app

  portainer-ce:
    image: portainer/portainer-ce:2.9.3
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=portainer.server.com
      - VIRTUAL_PORT=9000
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  portainer:
    extends:
      file: docker-common.yml
      service: apache
    volumes:
      - ./portainer/portainer.conf:/usr/local/apache2/conf/extra/portainer.conf
      - ./ssl/server.crt:/usr/local/apache2/conf/server.crt
      - ./ssl/server.key:/usr/local/apache2/conf/server.key
      - /var/run/docker.sock:/usr/local/apache2/portainer.sock
    depends_on:
      - portainer-ce

volumes:
  static:
  portainer_data: